services:

  # контейнер основного приложения
  lesta-games-app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      lesta-games-db:
        condition: service_healthy
    networks:
      - lesta

  # контейнер БД Postgres
  lesta-games-db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-54320}:5432"
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
    healthcheck:
      # https://www.postgresql.org/docs/current/app-pg-isready.html
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lesta

  # контейнер PGAdmin
  lesta-games-pg:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: always
    ports:
      - "${PGADMIN_PORT:-8888}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - lesta

  # контейнер Redis
  lesta-games-redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - lesta

  mongodb:
    container_name: lesta-games-mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - lesta

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - mongodb
    networks:
      - lesta

volumes:
  postgres_data:
    name: lesta_postgres_data
  dbdata6:
    name: lesta_mongodb_data


networks:
  lesta:
    driver: bridge
