services:

  # контейнер основного приложения
  lesta-games-app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    command: >
      sh -c "/wait-for-it.sh lesta-games-db:5432 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips=${ALLOW_ORIGINS}"
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      lesta-games-db:
        condition: service_healthy
    networks:
      - lesta

  # контейнер БД Postgres
  lesta-games-db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-54320}:5432"
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
    healthcheck:
      # https://www.postgresql.org/docs/current/app-pg-isready.html
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lesta

  # контейнер PGAdmin
  lesta-games-pg:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    restart: always
    ports:
      - "${PGADMIN_PORT:-8888}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - lesta-games-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lesta

  # контейнер Redis
  lesta-games-redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - lesta

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    restart: always
    networks:
      - lesta

  mongodb:
    image: mongo:7
    container_name: lesta-games-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
    volumes:
      - dbdata6:/data/db
    networks:
      - lesta

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_DB_ADMIN_USERNAME}:${MONGO_DB_ADMIN_PASSWORD}@mongodb:27017"
    depends_on:
      - mongodb
    networks:
      - lesta

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    networks:
      - lesta


  lesta-games-prometheus:
    image: prom/prometheus
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - lesta


  lesta-games-grafana:
    image: grafana/grafana
    container_name: ${GRAFANA_CONTAINER_NAME}
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - lesta

volumes:
  postgres_data:
    name: lesta_postgres_data
  dbdata6:
    name: lesta_mongodb_data
  portainer_data:
    name: lesta_portainer_data
  pgadmin_data:
    name: lesta_pgadmin_data
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data


networks:
  lesta:
    driver: bridge
