"""Add GuildWarRequest table

Revision ID: 4c2f7dde5ee5
Revises: 269b3e93b651
Create Date: 2025-07-01 18:33:12.109433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2f7dde5ee5'
down_revision: Union[str, None] = '269b3e93b651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_war_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_guild_id', sa.Integer(), nullable=True),
    sa.Column('target_guild_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', 'declined', 'canceled', 'expired', name='warstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiator_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['target_guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_war_requests_id'), 'guild_war_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_war_requests_id'), table_name='guild_war_requests')
    op.drop_table('guild_war_requests')
    # ### end Alembic commands ###
