"""add war history

Revision ID: a63dbd41781e
Revises: 4c2f7dde5ee5
Create Date: 2025-07-03 15:40:41.599667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63dbd41781e'
down_revision: Union[str, None] = '4c2f7dde5ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_war_requests_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('initiator_guild_id', sa.Integer(), nullable=True),
    sa.Column('target_guild_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', 'declined', 'canceled', 'expired', name='warstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_war_requests_history_id'), 'guild_war_requests_history', ['id'], unique=False)
    op.create_index(op.f('ix_guild_war_requests_history_initiator_guild_id'), 'guild_war_requests_history', ['initiator_guild_id'], unique=False)
    op.create_index(op.f('ix_guild_war_requests_history_request_id'), 'guild_war_requests_history', ['request_id'], unique=False)
    op.create_index(op.f('ix_guild_war_requests_history_target_guild_id'), 'guild_war_requests_history', ['target_guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_war_requests_history_target_guild_id'), table_name='guild_war_requests_history')
    op.drop_index(op.f('ix_guild_war_requests_history_request_id'), table_name='guild_war_requests_history')
    op.drop_index(op.f('ix_guild_war_requests_history_initiator_guild_id'), table_name='guild_war_requests_history')
    op.drop_index(op.f('ix_guild_war_requests_history_id'), table_name='guild_war_requests_history')
    op.drop_table('guild_war_requests_history')
    # ### end Alembic commands ###
