"""add roles_promotes

Revision ID: c27884beb6d4
Revises: b00992d40631
Create Date: 2025-07-06 11:11:39.541597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27884beb6d4'
down_revision: Union[str, None] = 'b00992d40631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_promotes',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('promote_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promote_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'promote_role_id')
    )
    
    op.execute("""    
        INSERT INTO roles_promotes (role_id, promote_role_id)
        SELECT r.id, p_r.id FROM roles r, roles p_r
        WHERE r.title = 'officer' AND p_r.title IN ('cabin_boy')
    """)
    
    op.execute("""    
        INSERT INTO roles_promotes (role_id, promote_role_id)
        SELECT r.id, p_r.id FROM roles r, roles p_r
        WHERE r.title = 'owner' AND p_r.title <> 'owner'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_promotes')
    # ### end Alembic commands ###
