"""change war id

Revision ID: dc0888ba7f00
Revises: b00992d40631
Create Date: 2025-07-06 18:19:24.585026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0888ba7f00'
down_revision: Union[str, None] = 'b00992d40631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_war_requests_history', sa.Column('war_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_guild_war_requests_history_request_id'), table_name='guild_war_requests_history')
    op.create_index(op.f('ix_guild_war_requests_history_war_id'), 'guild_war_requests_history', ['war_id'], unique=False)
    op.drop_column('guild_war_requests_history', 'request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_war_requests_history', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_guild_war_requests_history_war_id'), table_name='guild_war_requests_history')
    op.create_index(op.f('ix_guild_war_requests_history_request_id'), 'guild_war_requests_history', ['request_id'], unique=False)
    op.drop_column('guild_war_requests_history', 'war_id')
    # ### end Alembic commands ###
