class UncorrectGuildTagException(Exception):
    ...

class GuildNotFoundException(Exception):
    ...

class GuildAlreadyExistException(Exception):
    ...

class GuildIsFullException(Exception):
    ...