class MemberNotFoundException(Exception):
    ...

class MemberAlreadyInGuildException(Exception):
    ...
    
class MemberInOtherGuildException(Exception):
    ...

class MemberNotHavePermissionException(Exception):
    ...

class MemberIsNotOwnerException(MemberNotHavePermissionException):
    ...