name: Deploy Backend Lesta Guilds

on:
  push:
    branches:
      - main  # Только ветка main триггерит деплой

jobs:
  deploy:
    name: Deploy to Production Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Clean remote project directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/guilds/*

      - name: Upload all project files via rsync (no exclude)
        run: |
          rsync -avz \
            -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/guilds

      - name: Setup and deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo cp /var/www/guilds/.env.sample /var/www/guilds/.env
            cd /var/www/guilds
            sudo docker compose down
            sudo docker compose up -d --build