name: Deploy Backend Lesta Guilds

on:
  push:
    branches:
      - main  # Только ветка main триггерит деплой

jobs:
  deploy:
    name: Deploy to Production Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server via rsync over SSH
        uses: burnett01/rsync-deployments@v2
        with:
          switches: -avz --delete
          path: ./lesta_tz_backend/
          remote_path: /var/www/guilds
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup and deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo cp /var/www/guilds/.env.sample /var/www/guilds/.env
            cd /var/www/guilds
            sudo docker compose up -d --build